name: Deploy lemniscata.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.LEMNISCLOUD_DEPLOY_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: redstone
          SERVER_IP: ${{ secrets.LEMNISCLOUD_HOST }}
          APP_DIR: ${{ secrets.LEMNISCLOUD_WEB_ROOT }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          git remote set-url origin git@github.com:paurealm/lemniscata.git &&
          git pull origin main
          "